[[redirects]]
  from = "https://unilib-mbktechstudio.netlify.app/*"
  to = "https://unilib.mbktechstudio.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://unilib.mbktechstudio.com/*"
  to = "https://unilib.mbktechstudio.com/:splat"
  status = 301
  force = true
